# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftUIFirebasePractice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftUIFirebasePractice
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseStorage'
  pod 'Firebase'
  pod 'FirebaseFirestoreSwift'
  pod 'Kingfisher', '~> 7.0'
  pod 'CombineExt'
end

